# Generated by Django 5.1.2 on 2024-10-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_extra_price_list_size_topping_item_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_list',
            name='category',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.RemoveField(
            model_name='item_list',
            name='base_price_id',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item_List',
        ),
        migrations.DeleteModel(
            name='Price_List',
        ),
    ]
